### PR TITLE
Fix mode switch

### PR DESCRIPTION
**Pull request by ioio2995**
Hello,

Here is a new request. I have noticed that the `command_mode_switch` function allows multiple controllers to be active simultaneously on the same interface. I believe it would be preferable to perform some tests before executing the `perform_command_mode_switch` function. The use of the `prepare_command_mode_switch` function seems to address our issue.

`prepare_command_mode_switch` is a prerequisite for `perform_command_mode_switch`. In case of failure, a clear message is displayed in the logs:

```
[ros2_control_node-3] [ERROR] [1717748246.853741244] [MyActuatorRmdHardwareInterface]: Failed to switch to effort interface!
[ros2_control_node-3] [ERROR] [1717748246.853772188] [resource_manager]: Component 'joint_ros2_control' did not accept command interfaces combination:
[ros2_control_node-3] Start interfaces:
[ros2_control_node-3]   joint/effort
[ros2_control_node-3] Stop interfaces:
[ros2_control_node-3] 
[ros2_control_node-3] [ERROR] [1717748246.853778735] [controller_manager]: Could not switch controllers since prepare command mode switch was rejected.
```

Following this error, the execution of `perform_command_mode_switch` does not occur, and the `*interface_running` variables are not modified. In order to perform a mode switch, the interface must first be stopped by shutting down the controller responsible for its state.

I also took the opportunity to add the management of motor stop via a 0x81 when no controller is active. 

Best regards,

### CODE REVIEW

**Comment by 2b-t** [comment]
_Thank you @ioio2995,_
This was also on my list of issues to fix but was busy with the low-pass filter and some other minor changes.

**Comment by 2b-t** [comment]
I had a look at your code as well as a few examples online (e.g. Franka, UR and Elfin) and I am not fully sure what the best way to implement this is.

The [official documentation](https://control.ros.org/humble/doc/api/classhardware__interface_1_1ActuatorInterface.html#ac2723705913dcd8712549a2285cdf2d0) states:

- `prepare_command_mode_switch`:
  > This is a non-realtime evaluation of whether a set of command interface claims are possible, and call to start preparing data structures for the upcoming switch that will occur. All starting and stopping interface keys are passed to all components, so the function should return `return_type::OK` by default when given interface keys not relevant for this component.
- `perform_command_mode_switch`:
  > This is part of the realtime update loop, and should be fast. All starting and stopping interface keys are passed to all components, so the function should return `return_type::OK` by default when given interface keys not relevant for this component.

In the case of this actuator `prepare_command_mode_switch` would only check if we had a valid torque constant and but not even check if there are non-matching entries in the interfaces as the documentation states:
> Returns `return_type::OK` if the new command interface combination can be switched to, or if the interface key is not relevant to this system. Returns `return_type::ERROR` otherwise. 

So we would basically only loop over the `start_interfaces` and check if one of them corresponds to `start_interface == info_.joints.at(0).name + "/" + hardware_interface::HW_IF_EFFORT`. In case the torque constant is not set correctly we would make it fail as we will not be able to use the effort interface in pretty much every other case we would return success. We could also add the initialization of the low-pass filter to it in case one wanted to switch to an effort interface.

Then `perform_command_mode_switch` would perform the stop of all listed interfaces to be stopped followed by the start of all interfaces to be started **without ever stopping the motor**. This way one could immediately switch between e.g. position and effort control. In case there would be no `start_interfaces` provided that are relevant to us we stop the motor and make the thread not publish CAN commands any more. I have though not tested yet if that is actually a realistic an useful requirement but the way that I understand your code in your pull request we would have to first stop an interface and then start the other one.

I will test your code later today, merge it, potentially apply the changes above and then ask you for feedback. Collaborators on personal repositories on Github are unfortunately a bit of a pain otherwise I would invite you as a collaborator to this repository so that we could work together on a common feature branch.

**Comment by ioio2995** [comment]
I understand your point of view. 
I initiated this PR following the observation of the behavior mentioned and to prevent it from occurring. 
During my initial tests, I played around with starting multiple controllers simultaneously. 
During the bringup startup, the joint_trajectory_controller is started by default (the can dump correctly returns an A4). I then started the velocity_controller and the dump correctly returns an A2. I can control the speed of my motor by publishing to the /velocity_controller/commands topic. 
Naively, I thought it might be possible to continue using the joint_trajectory_controller. 
Unfortunately, no. When the velocity_controller starts, it switches my interface to velocity control and only switches back to position control by disabling the joint_trajectory_controller. When reactivated, the interface switches back to position control, which is logical. 
I had already observed this behavior and had corrected it via prepare_command_mode_switch by returning return_type::ERROR when the interface to switch is already active.

**Comment by 2b-t** [comment]
Just tested and merged your pull request. I made some minor modifications in e6dd8087bb6d0738a884f1196eee53c8a721ad6f so that we can switch between controllers without having go through stopping the motor as I suggested above. Now when calling e.g.
```
$ ros2 service call /controller_manager/switch_controller controller_manager_msgs/srv/SwitchController "{activate_controllers: [], deactivate_controllers: [], start_controllers: [velocity_controller], stop_controllers: [joint_trajectory_controller], strictness: 1, start_asap: false, activate_asap: false, timeout: {sec: 0, nanosec: 0}}"
```
you can immediately stop one and start another controller with a different command interface.
_Thanks again for your contribution!_

**Pull request merged**
